backend:
  image:
    repository: spidermanintegration/smart-fridge-backend
    tag: latest
  containerPort: 5000
  servicePort: 5000
  replicas: 1

frontend:
  image:
    repository: spidermanintegration/smart-fridge-frontend
    tag: latest
  containerPort: 80
  servicePort: 80
  replicas: 1

serviceType: LoadBalancer  # Changed to LoadBalancer for AWS EKS LoadBalancer service

notifier:
  image: 
    repository: spidermanintegration/smart-fridge-notifier
    tag: latest
    replicas: 1
