# k8s/argocd-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fridge-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kranthivodnala/smart-fridge
    targetRevision: HEAD
    path: fridge-app

  destination:
    server: https://BCDF6BB8CE8F758F531A089A74CF9E87.gr7.us-east-1.eks.amazonaws.com
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true