# k8s/argocd-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fridge-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kranthivodnala/smart-fridge
    targetRevision: HEAD
    path: fridge-app

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true